{% set name = "babelizer" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/bmi-forum/babelizer
  git_rev: v{{ version }}

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - nose
    - cca-babel <2
    - cca-bocca
    - pexpect

  run:
    - python
    - setuptools
    - pyyaml
    - nose
    - cca-babel <2
    - cca-bocca
    - pkg-config [osx]
    - pexpect
    - scripting

test:
  imports:
    - bmibabel
  commands:
    - bmi-find -h
    - bmi-babelize -h
    - bmi-parameters -h
    - bmi-files -h
    - bmi-stage -h
    - bmi-install -h
    - bmi -h
  requires:
    - cmake
    - conda-build
    - matplotlib
    - pymt

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - bmi-find=bmibabel.cmd.bmi_find:main
    - bmi-babelize=bmibabel.cmd.bmi_babelize:main
    - bmi-parameters=bmibabel.cmd.bmi_parameters:main
    - bmi-files=bmibabel.cmd.bmi_files:main
    - bmi-stage=bmibabel.cmd.bmi_stage:main
    - bmi-install=bmibabel.cmd.bmi_install:main
    - bmi=bmibabel.cmd.bmi:main
  preserve_egg_dir: True

about:
  home: https://github.com/bmi-forum/babelizer
  license: MIT
  license_file: LICENSE
  summary: Generate BMI language bindings with babel.
  dev_url: https://github.com/bmi-forum/babelizer
